### ISSUE TITLE
How do you dump offsets? any good tool please tell me

### ISSUE THREAD

**Issue by nadir1122** [atiksoftware/pubg_mobile_memory_hacking_examples#11]
Offsets change with every update. I wonder how do you dump those offsets for such this.

**Comment by atiksoftware** [comment]
firstly get UE4lib file in game files.
you can use MEMU or other basic emulators.
you can find file with FileManager apps.

copy file to your desktop from emulator
open file with IDA Pro.
you can see Gworld,Gname,viewport offsets
also you can look to https://github.com/kp7742/UE4Dumper/tree/master/SDKs here for dumped sdk
