### ISSUE TITLE
How to find pattern for viewMatrix in ldplayer with gnames and uworld

### ISSUE THREAD

**Issue by atulkunal999** [atiksoftware/pubg_mobile_memory_hacking_examples#12]
How to find pattern for viewMatrix in ldplayer with gnames and uworld

**Comment by mazid12345** [comment]
> How to find pattern for viewMatrix in ldplayer with gnames and uworld

**Comment by mazid12345** [comment]
[]()

**Comment by atiksoftware** [comment]
@atulkunal999 @mazid12345 
LDPlayer / MemuPlay / NoxPlayer and a few more emulators virtualbox. thats not working like Gameloop and smartgaga

i have a few methods for read virtualboxed systems memory (emulators and VMware OS), i cant share methods;
but i can just say to you; you cant read virtualbox memory

of course readable. you can find objects with pattern scanning in application memory.
buy you cant work on like direct hacking.
