### ISSUE TITLE
Hi atik!

### ISSUE THREAD

**Issue by BohanRen** [atiksoftware/pubg_mobile_memory_hacking_examples#2]
Thanks for sharing your code.It do work for me.But some offsets in your code are not disclosed.

`nameOffset`,`teamIDOffset` for example

Can you please send them to me or just commit them in your project, then I can make my own hacking. Thanks!

**Comment by atiksoftware** [comment]
@BohanRen you are right 

DWORD controllerOffset = 96;
DWORD posOffset = 336;
DWORD healthOffset = 1912;
DWORD nameOffset = 1512;
DWORD teamIDOffset = 1552;
DWORD statusOffset = 868;
DWORD poseOffset = 288;

i add to top of cpp file.

**Comment by BohanRen** [comment]
Thank you!
