### ISSUE TITLE
ReClass How read aow.exe memory

### ISSUE THREAD

**Issue by lmssky** [atiksoftware/pubg_mobile_memory_hacking_examples#3]
As the title says, aow.exe process is protected, can you tell me a way to bypass it thanks

**Comment by atiksoftware** [comment]
@lmssky actualy, you can find reClass driver plugin.
but i modified some things in reClass.
you can look here, i uploaded
https://github.com/atiksoftware/pubg_mobile_memory_hacking_examples/tree/master/ReClassModified

load kprocesshackers.sys driver. (KProcesshacker2 version. it should be 2.8.0~)

**Comment by lmssky** [comment]
@atiksoftware 
Please give me a usable program includes a driver, I do not very good at C ++ thank you

**Comment by lmssky** [comment]
@atiksoftware
My main aim is to find the version of the CN pubgm offset address，If you can give a copy would be great

**Comment by atiksoftware** [comment]
stay in follow me in youtube

**Comment by MirshadRI** [comment]
Any update for 0.18.0?
