### ISSUE TITLE
Can not find the window Gameloop with FindWindowEx function!

### ISSUE THREAD

**Issue by ledunggit** [atiksoftware/pubg_mobile_memory_hacking_examples#7]
Version game: 18.0
`LPCWSTR hwndText = L"Gameloop【Turbo AOW Engine-4.4】";`
	`LPCWSTR hwndClass = L"TXGuiFoundation";`
	`HWND hwndMain = FindWindowEx(NULL, NULL, hwndClass, hwndText);`
	`if (IsWindow(hwndMain)) `
	`{`
		`RECT rect;`
		`GetWindowRect(hwndMain, &rect);`
		`left = rect.left;`
		`top = rect.top;`
		`width = rect.right - rect.left;`
		`height = rect.bottom - rect.top;`
	`}`
	`else`
	`{`
		`left = 1;`
		`top = 1;`
		`width = GetSystemMetrics(SM_CXSCREEN) - 2;`
		`height = GetSystemMetrics(SM_CYSCREEN) - 2;`
	`}`

**Comment by atiksoftware** [comment]
i think you already fix it, i just want give answer.

Try find just with classname
or try listing all window titles, and be sure app can see gameloop.
because some times i see someones try find non administrator mod.
you need perms
